# Generated by Django 2.2.9 on 2021-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210215_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_phone',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='country',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='full_name',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='postal_code',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_name',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
